### ISSUE TITLE
Can XLora work fine or same if LoRA -> xLoRA complete: Swapped 0 LoRA layers:

### ISSUE THREAD

**Issue by Abdullah-kwl** [EricLBuehler/xlora#23]
i testing xlora with quantized and non quantized model 

case 1:
when I used non quantized model it shows output:
LoRA -> xLoRA complete: Swapped 96 LoRA layers (out of 1320 modules).

Case 2:
when I used 4bit quantized model it shows output:
LoRA -> xLoRA complete: Swapped 0 LoRA layers (out of 1320 modules).

but in both cases (Case 1 and Case 2) it shows that total trainable parameters are trainable%: 0.9182

if swapping is necessary then why total trainable parameters are not changing, or swaping problem can be due to quantized model.
Is xlora work same or fine if LoRA -> xLoRA complete: Swapped 0 LoRA layers?

If not can you update your code for 4bit quantized models?

![case_1](https://github.com/EricLBuehler/xlora/assets/101694671/91e7567e-796d-42d6-8746-b9fe791057b8)
![case_2](https://github.com/EricLBuehler/xlora/assets/101694671/d1d77272-94ea-449c-b59f-160b74d07db3)

**Comment by EricLBuehler** [comment]
@Abdullah-kwl, from #22:

> Hi Abdullah-kwl, the lack of swapping for a quantized model can be caused by internal QLora* layers. At the moment, xlora only supports non quantized layers. If you could provide a simple minimum reproducible code, that would be very helpful for future implementation of support for quantized layers.
